# Generated by Django 3.2.16 on 2026-05-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendation_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_outdoor', models.BooleanField(default=False)),
                ('task_type', models.CharField(choices=[('meeting', 'Meeting'), ('walk', 'Walk'), ('sport', 'Sport'), ('study', 'Study'), ('other', 'Other')], default='other', max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('google', 'Google Calendar')], default='manual', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
