# Generated by Django 3.2.16 on 2026-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_calendar', '0002_auto_20260515_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='need_remind',
            field=models.BooleanField(default=False, verbose_name='Напомнить заранее'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='remind_days_before',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='За сколько дней напомнить'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(choices=[('meeting', 'Встреча'), ('walk', 'Прогулка'), ('sport', 'Спорт'), ('study', 'Учеба'), ('other', 'Другое')], default='other', max_length=50),
        ),
    ]
