# Generated by Django 3.2.16 on 2026-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_sun_allergy',
            field=models.BooleanField(default=False, verbose_name='Чувствительность к солнцу / УФ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_dust_allergy',
            field=models.BooleanField(default=False, verbose_name='Аллергия на пыль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_pollen_allergy',
            field=models.BooleanField(default=False, verbose_name='Аллергия на пыльцу'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='magnetic_sensitivity',
            field=models.CharField(choices=[('low', 'Слабое влияние'), ('medium', 'Среднее влияние'), ('high', 'Сильное влияние')], default='low', max_length=10, verbose_name='Влияние магнитных бурь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_notification_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время уведомления'),
        ),
    ]
