# Generated by Django 3.2.16 on 2026-05-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='event',
        ),
    ]
