# Generated by Django 3.2.16 on 2026-05-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendation_event'),
        ('tasks_calendar', '0002_auto_20260515_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_calendar.tasks'),
        ),
    ]
